[versions]

agp = "8.11.1"

datastorePreferences = "1.1.7"
desugar_jdk_libs = "2.1.5"
foundation = "1.9.0"
gson = "2.13.1"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.5.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
lifecycleLivedataKtx = "2.9.2"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.08.00"

hilt = "2.57.1"
hiltNavigationCompose = "1.2.0"

#navigation
lifecycleViewmodelCompose = "2.9.2"
mockkAndroid = "1.14.5"
mockkVersion = "1.14.5"
moshiVersion = "1.15.2"
navigation = "2.9.3"

#firebase
firebaseBom = "33.16.0"

coil = "2.7.0"

playServicesLocation = "21.3.0"
reorderable = "0.9.6"
material3 = "1.3.2"
foundationLayout = "1.9.0"


okhttp = "5.1.0"


securitycrypto = "1.1.0"
browser = "1.9.0"
truthVersion = "1.4.2"
turbineVersion = "1.1.0"
ui = "4.0.0"
workRuntimeKtx = "2.10.3"
appcompat = "1.7.1"


coroutinesTest = "1.10.2"
turbine = "1.2.1"


retrofit = "3.0.0"

# 2) Moshi: quédate con una sola; aquí unifico a 'moshi'
moshi = "1.15.2"

# 3) AndroidX Test (runner/rules/core)
androidxTest = "1.6.1"

# 4) Aserciones y mocks
truth = "1.4.2"
mockk = "1.13.12"
junitKtx = "1.3.0"
uiTestJunit4 = "1.9.0"
espressoIntents = "3.7.0"
junitJupiter = "5.8.1"






[libraries]

converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
#noinspection SimilarGradleDependency
kotlinx-coroutines-test-v1101 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
mockk-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshiVersion" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiVersion" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

security-crypto = { module = "androidx.security:security-crypto", version.ref = "securitycrypto" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

google-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "21.4.0" }


hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx" }

reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
truth = { module = "com.google.truth:truth", version.ref = "truthVersion" }

ui = { module = "com.truelayer.payments:ui", version.ref = "ui" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }


adapter-rxjava3  = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }





[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt"}
